Authors/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.Author_list)
]

Catalog/urls.py
from django.conf.urls import url
from django.urls import path
from django.urls import re_path

from . import views
from django.contrib.auth.decorators import login_required
urlpatterns = [
    path('list/',views.Catalog_list),
    path('', views.index,name='index'),
    path('books/',views.BookListView.as_view(),name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('validate_username/',views.GetFileCode, name='validate_username'),
    path('authors/',views.AuthorListView.as_view(),name="authors"),
    path('author/<int:pk>',views.AuthorDetailView.as_view(),name="author-detail"),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path,include
from django.urls import re_path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Catalog/', include('Catalog.urls')),
    path('Authors/', include('Authors.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

Catalog/models.py
from django.db import models
from django.urls import reverse
import uuid  # Required for unique book instances
from django.contrib.auth.models import User


class Genre(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name
class Author(models.Model):
    """
    Model representing an author.
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ["last_name", "first_name"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular author instance.
        """
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return '{0}, {1}'.format(self.last_name, self.first_name)
class Book(models.Model):
    """
    Model representing a book (but not a specific copy of a book).
    """
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file.
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")

    def display_genre(self):
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        """
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = 'Genre'

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.

    def __str__(self):
        """
        String for representing the Model object.
        """
        return "{0}({1})".format(self.title,self.author.first_name)

    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('book-detail', args=[str(self.id)])
class BookInstance(models.Model):
    """
    Model representing a specific copy of a book (i.e. that can be borrowed from the library).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')

    class Meta:
        ordering = ["due_back"]

    def __str__(self):
        """
        String for representing the Model object
        """
        return '{0} ({1})'.format(self.id, self.book.title)

        from datetime import date
        @property
        def is_overdue(self):
            if self.due_back and date.today() > self.due_back:
                return True
            return False

class FileCode(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular book across whole library")
    FileCode = models.CharField(max_length=200)
    Src1=models.CharField(max_length=10)
    Src2=models.CharField(max_length=10)
    Src3=models.CharField(max_length=10)
    Des1=models.CharField(max_length=10)
    Des2=models.CharField(max_length=10)
    Des3=models.CharField(max_length=10)
    DepartureDate=models.DateField(null=True)
    RetrunDate=models.DateField(null=True)
    SpecialDigit=models.CharField(null=True, max_length=3),
    status=models.IntegerField(null=True)
    Discription=models.CharField(null=True,max_length=200)

    def __str__(self):
        """
        String for representing the Model object
        """
        return '{0} ({1})'.format(self.Des1)

Catalog/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime  # for checking renewal date range.


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check date is not in past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check date is in range librarian allowed to change (+4 weeks).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

Catalog/views.py
from django.shortcuts import render
from .models import Book,BookInstance,Author,Genre,FileCode
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse;
from django.core import serializers;
from django.http import HttpResponse;
import json;

def Valid_Author(request):
    authName=request.GET.get('authName',None);
    num_books = Book.objects.all().count()
    num_visits = request.session.get('num_visits', 0);
    request.session['num_visits'] = num_visits + 1;
    data  ={
            'num_visits':num_visits
    }
    return JsonResponse(data)

def GetFileCode(request):
    # FileCode = request.GET.get('authName',None);
    if request.method == 'POST':
        Groups=list(json.loads(request.POST.get('deal',None)))
        for i in range(len(Groups)):
            bo=Book(title=Groups[i]['title'],
                    summary=Groups[i]['summary'],
                    isbn=Groups[i]['isbn'],
                    author_id=Groups[i]['author_id'])
            TestExist = Book.objects.filter(title__exact=Groups[i]['title']).count();
            if(TestExist==0):
                 bo.save();
        # Groups = Genre.objects.filter(id__exact=1).update(title=FileCode);
        Groups=Book.objects.all();
        lists=[1,2,3,4]
        # Groups_serialized = serializers.serialize('json', Groups)
        data =Groups;
    return HttpResponse(serializers.serialize("json", data),
                        content_type='application/json')


class BookListView(LoginRequiredMixin,generic.ListView):
    model = Book
class BookDetailView(LoginRequiredMixin,generic.DetailView):
    model = Book
class AuthorListView(generic.ListView):
    model = Author;
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(AuthorListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['MyBooks'] =Book.objects.all()
        return context

    template_name = 'Catalog/Author_list.html'
class AuthorDetailView(generic.DetailView):
    model = Author;
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(AuthorDetailView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['MyBooks'] = Book.objects.filter(author__last_name__contains='kanabi');
        return context

    template_name = 'Catalog/Author_detail.html'

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
        """
        Generic class-based view listing books on loan to current user.
        """
        model = BookInstance
        template_name = 'Catalog/bookinstance_list_borrowed_user.html'
        paginate_by = 10

        def get_queryset(self):
            return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by(
                'due_back')
# Create your views here.
def Catalog_list(requst):
    return render(requst,'Catalog/Catalog_list.html');
def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.all().count()  # The 'all()' is implied by default.
    BookPerAuthor=Book.objects.all().filter(author__last_name__contains='kanabi');
    num_visits = request.session.get('num_visits',0);
    request.session['num_visits'] =num_visits+1;
    return render(
        request,
        'Catalog/index.html',
        context ={
            'num_visits':num_visits,
            'num_books':num_books,'num_instances':num_instances,'num_instances_available':num_instances_available,'num_authors':num_authors},
    )


from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime


from .forms import RenewBookForm
@permission_required('Catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    """
    View function for renewing a specific BookInstance by librarian
    """
    book_inst=get_object_or_404(BookInstance, pk = pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date,})

    return render(request, 'catalog/book_renew_librarian.html',
                  {'form': form,
                   'bookinst':book_inst})

Catalog/templates/Catalog/Author_detail.html
{% extends "Catalog/base_generic.html" %}

{% block content %}
  <h1>Title: {{ author.first_name}}({{author.last_name}})</h1>

  <p><strong>Author First Name:</strong>{{ author.first_name }}</p> <!-- author detail link not yet defined -->
  <p><strong>Author Last Name:</strong> {{ author.last_name }}</p>
  <p><strong>Author date of birth:</strong> {{ author.date_of_birth }}</p>
  <p><strong>Author date of death:</strong> {{ author.date_of_death }}</p>

 <!--<div style="margin-left:20px;margin-top:20px">-->
    <!--<h4>Copies</h4>-->
<!--{{MyBooks}}-->
{%for b in MyBooks%}
<i>{{b}}</i><br>
{%endfor%}
    <!--{% for copy in author.book_set.all %}-->
    <!--<hr>-->
    <!--<p><strong>Summary:</strong> {{ copy.summary }}</p>-->
  <!--<p><strong>ISBN:</strong> {{ copy.isbn }}</p>-->
  <!--<p><strong>Language:</strong> {{ copy.language }}</p>-->
    <!--{% endfor %}-->
  <!--</div>-->
{% endblock %}

Catalog/templates/Catalog/Author_list.html
{% extends "Catalog/base_generic.html" %}
{% block content %}
    <h1>Author List</h1>

    {% if author_list %}
    <ul>

      {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.last_name }}</a> ({{author.first_name}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}

<input type="button" value="ok">
 <input type="text" >
{% endblock %}

Catalog/templates/Catalog/Catalog_List.html
{% extends "Catalog/base_generic.html" %}

{% block content %}
<h1>Local Library Home</h1>

  <p>Welcome to <em>LocalLibrary</em>, a very basic Django website developed as a tutorial example on the Mozilla Developer Network.</p>

<h2>Dynamic content</h2>

  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
  </ul>

{% endblock %}

Catalog/templates/Catalog/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
  <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>-->
  <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
<!--<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.min.js"></script>-->
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
     <script src="{% static 'scripts/jquery.js' %}" ></script>
     <script src="{% static 'scripts/angular.min.js' %}" ></script>
    <script src="{% static 'scripts/demo.js' %}" ></script>
</head>

<body ng-app="myApp" ng-controller="MyController">

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
          <input id="id_username"/>
          {% csrf_token %}
          <input type="button" id="btn" value="changeColor" ng-click="PostBook()">
      {% block sidebar %}
      <ul class="sidebar-nav">
      {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
           <li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li>
     <li><a href="{% url 'logout'%}?next={% url 'login'%}">Logout</a></li>
      {% else %}
     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
     {% endif %}
   {% if user.is_authenticated %}
          <li><a href="{% url 'index' %}">Home</a></li>

          <li><a href="{% url 'books' %}">All books</a></li>

          <li><a href="{% url 'authors' %}">All authors</a></li>
          <li ng-repeat="c in DatedVault">

              <h4>[[c.fields.title]]-[[c.fields.summary]]</h4>


          </li>
 {%endif%}
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>

  </div>

{% block javascript %}
  <script>
    <!--$("#id_username").change(function () {-->
      <!--var username = $(this).val();-->

      <!--$.ajax({-->
        <!--url: 'validate_username/',-->
        <!--data: {-->
          <!--'authName': username-->
        <!--},-->
        <!--dataType: 'json',-->
        <!--success: function (data) {-->

            <!--alert("A user with this username already exists."+data.num_visits);-->

        <!--}-->
      <!--});-->

    <!--});-->
  </script>
{% endblock %}

</body>



<script>

<!--$('#btn').click(function(){-->
 <!--$.ajax({url: "http://127.0.0.1:8000/Catalog/",-->
         <!--success: function(result){-->
        <!--$("#spn").html(result);-->
    <!--}});-->
<!--});-->
<!--('#btn').click(function(){-->
 <!--$.ajax({url: "http://127.0.0.1:8000/Catalog/",-->
         <!--success: function(result){-->
        <!--$("#spn").html(result);-->
    <!--}});-->
<!--});-->

</script>
</html>

Catalog/templates/Catalog/book_detail.html
{% extends "Catalog/base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Language:</strong> {{ book.language }}</p>  
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

Catalog/templates/Catalog/book_list.html
{% extends "Catalog/base_generic.html" %}

{% block content %}
    <h1>Book List</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

Catalog/templates/Catalog/book_renew_librarian.html
{% extends "Catalog/base_generic.html" %}
{% block content %}

    <h1>Renew: {{bookinst.book.title}}</h1>
    <p>Borrower: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{bookinst.due_back}}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

Catalog/templates/Catalog/bookinstance_list_borrowed_user.html
{% extends "Catalog/base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

Catalog/templates/Catalog/index.html
{% extends "Catalog/base_generic.html" %}

{% block content %}
<h1>Local Library Home</h1>

  <p>Welcome to <em>LocalLibrary</em>, a very basic Django website developed as a tutorial example on the Mozilla Developer Network.</p>

<h2>Dynamic content</h2>

  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>

    <li>All books:
    <ul>
      <p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>

      {% for item in BookPerAuthor%}
      <li>{{item}}</li>
      {%endfor%}
    </ul>
    </li>

  </ul>

{% endblock %}